import { ExerciseRecord } from './types';

export const exerciseTypeNames = {
  walking: '걷기',
  stretching: '스트레칭',
  balance: '균형 잡기',
  sitting: '앉기/서기',
  standing: '서기 운동',
  walkingSupport: '보행 보조',
  jogging: '조깅',
  cycling: '자전거',
};

export const exerciseIcons = {
  walking: '🚶‍♂️',
  stretching: '🧘‍♂️',
  balance: '⚖️',
  sitting: '🪑',
  standing: '🧍‍♂️',
  walkingSupport: '🦯',
  jogging: '🏃‍♂️',
  cycling: '🚴‍♂️',
};

export const difficultyColors = {
  easy: '#4CAF50',
  normal: '#FF9800',
  hard: '#F44336',
};

export const difficultyNames = {
  easy: '쉬움',
  normal: '보통',
  hard: '어려움',
};

export const mockExerciseHistory: ExerciseRecord[] = [
  {
    id: '1',
    date: '2024-01-15',
    time: '09:30',
    type: 'indoor',
    subType: 'walking',
    name: '실내 걷기 운동',
    duration: 20,
    steps: 1847,
    distance: 1.1,
    calories: 85,
    painBefore: 3,
    painAfter: 2,
    notes: '무릎 상태가 많이 좋아짐',
    completionRate: 95,
    difficulty: 'normal',
  },
  {
    id: '2',
    date: '2024-01-15',
    time: '15:45',
    type: 'indoor',
    subType: 'stretching',
    name: '스트레칭',
    duration: 15,
    painBefore: 4,
    painAfter: 2,
    completionRate: 100,
    difficulty: 'easy',
  },
  {
    id: '3',
    date: '2024-01-14',
    time: '08:15',
    type: 'outdoor',
    subType: 'walking',
    name: '공원 산책',
    duration: 35,
    steps: 3247,
    distance: 2.1,
    calories: 156,
    avgHeartRate: 78,
    maxHeartRate: 92,
    painBefore: 2,
    painAfter: 3,
    notes: '날씨가 좋아서 평소보다 오래 걸었음',
    completionRate: 100,
    difficulty: 'normal',
  },
  {
    id: '4',
    date: '2024-01-13',
    time: '10:20',
    type: 'indoor',
    subType: 'balance',
    name: '균형 잡기 운동',
    duration: 12,
    painBefore: 2,
    painAfter: 2,
    completionRate: 80,
    difficulty: 'hard',
  },
  {
    id: '5',
    date: '2024-01-12',
    time: '16:30',
    type: 'outdoor',
    subType: 'walking',
    name: '동네 한바퀴',
    duration: 25,
    steps: 2156,
    distance: 1.4,
    calories: 98,
    avgHeartRate: 75,
    maxHeartRate: 88,
    painBefore: 3,
    painAfter: 3,
    completionRate: 100,
    difficulty: 'easy',
  },
];